apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tensorbeat
  name: datalake
spec:
  selector:
    matchLabels:
      app: datalake
  template:
    metadata:
      labels:
        app: datalake
    spec:
      containers:
      - name: datalake
        image: gcr.io/rowan-senior-project/tensorbeat-datalake:v1.0.0
        env:
          - name: PORT
            value: "50051"
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongo-uri
                key: mongo-uri
          - name: ENVIRONMENT
            value: "prod"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: datalake
spec:
  type: ClusterIP
  selector:
    app: datalake
  ports:
  - port: 50052
    targetPort: 50051
    name: grpc-web
  - port: 50051
    targetPort: 50051
    name: grpc
